name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test docker image
        run: docker build --target test --tag todo-app-test .
      - name: Unit tests
        run: docker run todo-app-test tests/unit_tests
      - name: Integration tests
        run: docker run todo-app-test tests/integration_tests
      - name: End to end tests 
        run:  docker run -e MONGO_CONNECTION_STRING="${{ secrets.MONGO_CONNECTION_STRING }}" todo-app-test tests_e2e
  deploy:
    name: Publish and deploy
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kirstyland
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Build docker image
        run: docker build --target production --tag kirstyland/todo-app:latest --tag kirstyland/todo-app:$GITHUB_SHA .
      - name: Push docker image to docker
        run: docker push --all-tags kirstyland/todo-app
      - name: Initialize terraform
        run: terraform init
      - name: Apply terraform
        run:  terraform apply -auto-approve
      - name: Restart Azure app
        run: curl -dH -X POST "$(terraform output -raw webhook_url)"
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      TF_VAR_prefix: prod
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      TF_VAR_oauth_client_id: ${{ secrets.OAUTH_CLIENT_ID }}
      TF_VAR_oauth_client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
      TF_VAR_writer_user_ids: ${{ secrets.WRITER_USER_IDS }}
