name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test docker image
        run: docker build --target test --tag todo-app-test .
      - name: Unit tests
        run: docker run todo-app-test tests/unit_tests
      - name: Integration tests
        run: docker run todo-app-test tests/integration_tests
      - name: End to end tests 
        run:  docker run -e TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} -e TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }} -e TRELLO_ORGANIZATION_ID=${{ secrets.TRELLO_ORGANIZATION_ID }} todo-app-test tests_e2e
  deploy:
    name: Publish and deploy
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kirstyland
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Build docker image
        run: docker build --target production --tag kirstyland/todo-app:latest --tag kirstyland/todo-app:$GITHUB_SHA .
      - name: Push docker image to docker
        run: docker push --all-tags kirstyland/todo-app
      - name: Restart Azure app
        run: curl -dH -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
