name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test docker image
        run: docker build --target test --tag todo-app-test .
      - name: Unit tests
        run: docker run todo-app-test tests/unit_tests
      - name: Integration tests
        run: docker run todo-app-test tests/integration_tests